### ISSUE TITLE
 'Net' object has no attribute '_blob_names_index'

### ISSUE THREAD

**Issue by vex1286** [samson-wang/dcgan.caffe#1]
Hello, 
I have one problem when running your code in train.py, line 60. 

discr_loss_weight = discriminator.net._blob_loss_weights[discriminator.net._blob_names_index['discr_loss']]

I got AttributeError, 'Net' object has no attribute '_blob_names_index'
How can I run this code correctly?

**Comment by samson-wang** [comment]
@vex1286 
You should use the https://github.com/dosovits/caffe-fr-chairs/tree/deepsim branch of caffe.
Just checkout the deepsim branch of caffe, and compile it. Then `export PYTHONPATH=/path/to/deepsim/caffe/python:$PYTHONPATH`. The train.py should be running correctly then.

You'd better read the `Dependency` section of the readme again.

**Comment by vex1286** [comment]
@samson-wang 
Thank you for your reply, I will use this branch and try again.

**Comment by samson-wang** [comment]
@vex1286 
Have you got the train running?

**Comment by vex1286** [comment]
@samson-wang 
Yep. It works well now. Thank you very much.

**Comment by pauldelmusica** [comment]
Hi,

  I tried to merge Dosovitskiy's code with Caffe on Windows and got this error when I tried to do training.

  Has this merge been done before? I thought there aren't too much work. But obviously, I have missed a chunk of it.  I could not find where "_blob_names_index" is defined. Can someone give me a pointer?

**Comment by samson-wang** [comment]
@pauldelmusica It's in `python/caffe/_caffe.cpp`

**Comment by pauldelmusica** [comment]
Thanks! It is training now.

**Comment by ming1144** [comment]
Hi,

I still have problem while training.

My environment is Ubuntu 16, Cuda 8.0 , cudnn 5.1

I clone caffe from deepsim and switch to the branch.

To compile deepsim I disable cudnn and compiled well.

But the problem still occured.

Could you help me solve the problem?

**Comment by samson-wang** [comment]
@ming1144 Could you post your error message?
You'd better print your `caffe.__file__`. And make sure you are using the right caffe lib.

**Comment by ming1144** [comment]
python train.py error msg:
Traceback (most recent call last):
  File "train.py", line 60, in <module>
    discr_loss_weight = discriminator.net._blob_loss_weights[discriminator.net._blob_names_index['discr_loss']]
AttributeError: 'Net' object has no attribute '_blob_names_index'

deepsim error msg:
print caffe.__file__
/home/mmplab/git/caffe-dcgan/python/caffe/__init__.pyc

I've replaced deepsim name as caffe-dcgan

**Comment by samson-wang** [comment]
@ming1144 It's weird.
`caffe.file` is an invalid attribute.
It should be `print caffe.__file__`
and output should be `/home/core/deploy/caffe/python/caffe/__init__.py`

You can search in `/home/mmplab/git/caffe-dcgan/python/caffe/_caffe.cpp` to make sure that `_blob_names_index` exists.

**Comment by ming1144** [comment]
@samson-wang 
You are right.

_blob_names_index didn't show in _caffe.cpp

And the reason it didn't exist is that I clone the master branch of deepsim
_blob_names_index only appear in deepsim branch

This problem has been done.
Thanks to your supply.

**Comment by pauldelmusica** [comment]
I was doing it on Windows 10. I recall the code merging wasn't complete
when I had this message. It went away after I completed merging the code.

**Comment by 2017develper** [comment]
i try to solve this in windows but the same problem it show 

 discr_loss_weight = discriminator.net._blob_loss_weights[discriminator.net._blob_names_index['discr_loss']]
AttributeError: 'Net' object has no attribute '_blob_names_index'

**Comment by samson-wang** [comment]
@2017develper Please refer to `ming1144`'s comments
