### ISSUE TITLE
something wrong with the train.py

### ISSUE THREAD

**Issue by caney1989** [samson-wang/dcgan.caffe#2]
Hi
  I have compile the caffe-fr-chairs and test it. But  when i try to run the train.py , i find some problems about it: 
   1. i cannot understand the use of 'net.forward_simple' and 'net.backward_simple' and never find it in google.
   2. There is a valueerror in line 78, which note that "could not broadcast input array from shape (64,3,218,178) into shape (64,3,64,64)" 
 could you give me  some guidance to solve that ？？
 thank you!!

**Comment by samson-wang** [comment]
@caney1989  Any details?

**Comment by caney1989** [comment]
HI:
   I have edited the bug details. I am newly to this filed so maybe make some simple errors. could you give me some guidance to solve this problem ？
  Sincerely look forward to your reply. Thanks!!

**Comment by samson-wang** [comment]
@caney1989 
1. `forward_simple` is a function implemented in `caffe-fr-chairs`. It differs a bit from the `forward` in master branch. The `chairs` branch aims to give more fine-grained training control in python. You can start from  https://github.com/dosovits/caffe-fr-chairs/blob/deepsim/python/caffe/pycaffe.py#L309

2. All your images' size should be `64x64`, which is specified in https://github.com/samson-wang/dcgan.caffe/blob/master/discriminator.prototxt

**Comment by caney1989** [comment]
Thanks for you reply, but  i cannot understand how to solve it  by 'You can start from https://github.com/dosovits/caffe-fr-chairs/blob/deepsim/python/caffe/pycaffe.py#L309' as you say.
I am debugging caffe by pycharm. when debug the official version, i always add the pythonpath 'caffe/python' to the project. But this method is invalid to this 'caffe-fr-chairs'. Line60 reported 'attributeerror: Net object has no attribute ‘_blob_names_index’' and line68 reported ''attributeerror: Net object has no attribute ‘forward_simple' ".  I think the path  is incorrect but don't know  how to  configure it .
could you give me some guidance ？？
thank you!!

**Comment by samson-wang** [comment]
@caney1989 
I received an Email notification last night. However, the comment didn't show here. Have you solved the problem?
I have no experience with pycharm. Basically, you can debug with plain python by adding `print` to anywhere suspicious in the code. If the code suggested `no attribute`, the most possibility is that wrong pycaffe used or wrong caffe branch used.

Please make sure that you checkout the **`deepsim`** branch. The default branch is `master`, and no `forward_simple` has been implemented.

**Comment by caney1989** [comment]
I have solved it . Thank you very much for your help!!
