### ISSUE TITLE
Only updating discriminator on generated data

### ISSUE THREAD

**Issue by mattragoza** [samson-wang/dcgan.caffe#3]
I am trying to understand this code but I'm not quite getting how it works. In train.py you do a forward and backward pass of the discriminator with batches of real data and generated data, but you only call apply_update() after seeing generated data. Doesn't this mean the discriminator is never trained to classify real data, so the generated data won't necessarily match the real data distribution? But the output images seem realistic so I'm not sure what I'm missing.

**Comment by samson-wang** [comment]
@mattragoza  FYI
https://github.com/samson-wang/dcgan.caffe/blob/master/train.py#L83
https://github.com/samson-wang/dcgan.caffe/blob/master/train.py#L92
It did two `backward` before `apply_update`.
The diff will be accumulated. It's a feature of caffe framework.
You can notice that a `clear_param_diffs` called before `backward` at https://github.com/samson-wang/dcgan.caffe/blob/master/train.py#L82
