### ISSUE TITLE
Defining different discriminator-loss

### ISSUE THREAD

**Issue by Jee-King** [samson-wang/dcgan.caffe#6]
Hi, thanks for your work.
Could you explain the reason for defining `discr_real_loss, discr_fake_loss and discr_real_for_generator_loss`  in `train.py`. I can not understand the their differences, specifically `input 'data'` and `'label'`. 
Thank you very much!

**Comment by samson-wang** [comment]
Please refer to the comments:
https://github.com/samson-wang/dcgan.caffe/blob/master/train.py#L74

https://github.com/samson-wang/dcgan.caffe/blob/master/train.py#L85

https://github.com/samson-wang/dcgan.caffe/blob/master/train.py#L95

The discriminator predict on different data input.

**Comment by Jee-King** [comment]
Thank you very much!!
